### ISSUE TITLE
Feature Request: Harvest Report Request

### ISSUE THREAD

**Issue by joelsteidl** [Pr0ject-X/px#34]
I didn't see the harvest plugin on GH yet, so adding this here.

I often use a report like this:
https://atendesigngroup.harvestapp.com/reports/detailed?utf8=%E2%9C%93&group=dates&billable=yes&users%5B%5D=605293&start_date=2020-04-13&end_date=2020-04-19

It shows all billable hours (plus line items) for the current week. You can't bookmark it because of the dates generated by the "This week" filter.

- `px harvest:current-week`
- `px harvest:last-week`

**Comment by droath** [comment]
@joelsteidl Thanks for your interest in the Harvest integration. Project-X is focused on project specific integrations that only targets a single project. We've rolled out Harvest integration in our Jira plugin for issue/time tracking. 

Please check out a separate project that we're working on that's more dedicated to harvest https://github.com/droath/harvest-toolkit
