### ISSUE TITLE
Allow user to use Drush command

### ISSUE THREAD

**Issue by tiarastore** [Pr0ject-X/px#37]
Project-x commands currently use shortcut `drupal` to prepend drush commands. User would like option to use `drush` instead of `drupal` on px projects to prepend Drush commands. Drush may be more familiar muscle-memory to some Drupal users as a cmd line tool.

**Comment by tiarastore** [comment]
Noticing this setting is not part of `px` repo, but set in another repo belonging to part of [Project-X](https://github.com/Pr0ject-X). I am not sure which plugin it resides in. @droath

**Comment by droath** [comment]
@kyletcook Thanks, I'll move this issue into the PX Drupal plugin project.

**Comment by droath** [comment]
Issue has been moved. https://github.com/pr0ject-x/px-drupal/issues/8
